# in _config.yml
title: "Python essentials for GIS learners"
logo: images/logo.png
author: TU Delft DCC
execute:
  execute_notebooks: "off"

only_build_toc_files: true

exclude_patterns: [ 02_Python_Draw_GIS/code/** images/**.*,./**/*.py, ./**/*.jpg, LICENSE.md ]

# Information about where the book exists on the web
repository:
  url  : git@github.com:TU-Delft-DCC/Intro-to-Python-for-GIS.git

html:
  use_repository_button: true
  comments:
    utterances:
      repo: "TU-Delft-DCC/Intro-to-Python-for-GIS" 
    
  use_edit_page_button: true

  extra_footer: |
      Licensed under CC-BY 4.0 by The TU Delft DCC</br>
      <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
  
  
  
  home_page_in_navbar: true

sphinx:
    config:
      html_show_copyright: false