# in _config.yml
title: "Python essentials for GIS learners"
logo: images/logo.png
execute:
  execute_notebooks: "off"

only_build_toc_files: true

exclude_patterns: [LICENSE.md, 02_Python_Draw_GIS/code/** images/**.*,./**/*.py, ./**/*.jpg ]

# Information about where the book exists on the web
repository:
  url  : git@github.com:TU-Delft-DCC/Intro-to-Python-for-GIS.git

html:
  use_repository_button: true
  comments:
    utterances:
      repo: "TU-Delft-DCC/Intro-to-Python-for-GIS" 
  
  home_page_in_navbar: false
